name: Flutter Build

on:
  push:
    branches:  master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2


        
    - name: Change to drinkshop directory
      run: dir



