name: Build APK for drinkshop

on:
  push:
    branches:
      - master  # 或者你想要触发构建的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 'openjdk@1.8'  # 或者你需要的Java版本

    - name: Install Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.0.0'  # 指定你想要的Flutter版本

    - name: Change to drinkshop directory
      run: cd drinkshop

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: drinkshop-artifacts
        path: drinkshop/build/app/outputs/flutter-apk/

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "drinkshop/build/app/outputs/flutter-apk/*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
